---
# starting from the "simple" preset gives us:
# - the Conventional Commits convention
preset: "simple"
changelog:
  path: "CHANGELOG.md"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
releaseTypes:
  enabled:
    - mainline
    - maturity
    - internal
  publicationServices:
    - github
  items:
    mainline:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(master|main)$"
      matchEnvironmentVariables:
        CI: "^true$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
    maturity:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(alpha|beta)(\\.([0-9]\\d*))?)?$"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(alpha|beta)$"
      matchEnvironmentVariables:
        CI: "^true$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
    internal:
      collapseVersions: true
      collapsedVersionQualifier: "internal"
      gitPush: "false"
      gitTag: "false"
      identifiers:
        -
          qualifier: "{{#timestampYYYYMMDDHHMMSS}}{{timestamp}}{{/timestampYYYYMMDDHHMMSS}}"
          position: "BUILD"
      publish: "false"
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "dhis2-rule-engine"
      REPOSITORY_OWNER: "dhis2"