package org.hisp.dhis.rules.models


abstract class RuleActionText : RuleAction() {

    /**
     * @return a static content which will
     * be shown to the user.
     */
    abstract var content: String?

    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    abstract var data: String?

    /**
     * @return location of where the result of this
     * action must be rendered: can be either 'feedback'
     * or 'program indicator' widget.
     */
    abstract var location: String?

    companion object {
        const val LOCATION_FEEDBACK_WIDGET = "feedback"

        const val LOCATION_INDICATOR_WIDGET = "indicators"
    }
}
