package org.hisp.dhis.rules.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import javax.annotation.Nonnull;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type( value = AutoValue_RuleActionSendMessage.class, name = "RuleActionSendMessage" ),
        @JsonSubTypes.Type( value = AutoValue_RuleActionAssign.class, name = "RuleActionAssign" ),
        @JsonSubTypes.Type( value = AutoValue_RuleActionScheduleMessage.class, name = "RuleActionScheduleMessage" ),
})
public abstract class RuleAction
{

    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    @Nonnull
    @JsonProperty( "data" )
    public abstract String data();

    protected RuleAction()
    {
        // stub implementation
    }
}
