package org.hisp.dhis.rules.models;

import javax.annotation.Nonnull;

public abstract class RuleActionData
    extends RuleAction
{
    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    @Nonnull
    public abstract String data();
}
