package org.hisp.dhis.rules.models;

import javax.annotation.Nonnull;

public abstract class RuleAction
{

    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    @Nonnull
    public abstract String data();

    protected RuleAction()
    {
        // stub implementation
    }
}
