package org.hisp.dhis.rules.models;

import javax.annotation.Nonnull;

public interface RuleAction
{

    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    @Nonnull
    String data();
}
