on:
  workflow_call:
    outputs:
      isNewVersion:
        description: "Indicates if this build generates a new version"
        value: ${{ jobs.check-new-version.outputs.isNewVersion }}

jobs:
  check-new-version:
    name: Check new version
    runs-on: ubuntu-latest
    outputs:
      isNewVersion: ${{ steps.newVersion.outputs.isNewVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - id: newVersion
        name: Check new version
        run: ./.github/workflows/scripts/check-new-version.sh