on:
  workflow_call

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Create tag and publish Github release
        run: ./gradlew :nyxPublish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Maven
        run: ./.github/workflows/scripts/publish-maven.sh
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}

      - name: Publish NPMJS
        run: ./.github/workflows/scripts/publish-npm.sh
        env:
          NPMJS_TOKEN: ${{ secrets.DHIS2_BOT_NPM_TOKEN }}