name: Merge to Master

on:
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test
        run: mvn clean install -DskipTests=false --update-snapshots -q

  artifact:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Remove snapshot
        run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PGP_PASSPHRASE }}
          maven_profiles: "master"
