name: Publish NPM beta

on:
  workflow_dispatch

jobs:
  publish:
    name: Publish NPM beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Publish NPMJS
        run: ./.github/workflows/scripts/publish-npm-beta.sh
        env:
          NPMJS_TOKEN: ${{ secrets.DHIS2_BOT_NPM_TOKEN }}
